openapi: "3.0.3"
info:
  title: Order API
  version: "1.0.1"
servers:
  - url: http://127.0.0.1:80
paths:
  /api/orders:
    post:
      tags:
        - Order
      summary: Create order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
              example:
                product_id: 1
                quantity: 5
      responses:
        "201":
          description: Order created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                      total_price:
                        type: number
                    example:
                      product_id: 1
                      quantity: 5
                      total_price: 25000
        "400":
          description: Bad Request - Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                example:
                  errors:
                    product_id: [The product_id field is required]
        "404":
          description: Data not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                example:
                  errors:
                    message: [Data not found]
        "409":
          description: Conflict error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                example:
                  errors:
                    message: [Product's stock is unavailable]
